import google.generativeai as genai
from config.settings import GEMINI_API_KEY
from reflective_agent import run_reflective_agent
from react_agent import run_react_agent

genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel('models/gemini-2.5-flash')

def ai_agent(prompt):
    """
    A simple AI agent function that processes a given prompt and returns a response.
    
    Args:
        prompt (str): The input prompt for the AI agent.

    Returns:
        str: The response generated by the AI agent.
    """
    response = model.generate_content(prompt)
    print("Agent reply: \n", response.text)
    
    
if __name__ == "__main__":
    user_prompt = input("Enter your prompt: ")
    print("\n --- simple AI agent response --- \n")
    ai_agent(user_prompt)
    
    print("\n --- reflective AI agent response --- \n")
    reflective_response = run_reflective_agent(user_prompt)
    print(reflective_response)
    
    print("\n --- reactive AI agent response --- \n")
    reactive_response = run_react_agent(user_prompt)
    print(reactive_response)