import google.generativeai as genai
from config.settings import GEMINI_API_KEY

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('models/gemini-2.5-flash')

def run_react_agent(prompt: str) -> str:
    """
    A reactive AI agent that processes a given prompt and returns a response.
    
    Args:
        prompt (str): The input prompt for the reactive AI agent.

    Returns:
        str: The response generated by the reactive AI agent.
    """
    plan_prompt = f"You are an expert AI planner. Break down the following task into clear steps:\n\n{prompt}\n\nProvide a step-by-step plan."

    plan = model.generate_content(plan_prompt).text
    print("Generated Plan: \n", plan)

    reasoning_prompt = f"Based on the following plan, provide a detailed response to the original prompt:\n\nPlan:\n{plan}\n\nOriginal Prompt:\n{prompt}"

    reasoning = model.generate_content(reasoning_prompt).text
    print("Generated Reasoning: \n", reasoning)
    
    reflection_prompt = f"Review the following reasoning for improvements:\n\n{reasoning}\n\nProvide a revised version with enhancements."

    reflection = model.generate_content(reflection_prompt).text
    print("Generated Reflection: \n", reflection)

    return reflection