import google.generativeai as genai
from config.settings import GEMINI_API_KEY


genai.configure(api_key=GEMINI_API_KEY)

model = genai.GenerativeModel('models/gemini-2.5-flash')

def run_reflective_agent(prompt):
    """
    A reflective AI agent that processes a given prompt and returns a response.
    
    Args:
        prompt (str): The input prompt for the reflective AI agent.

    Returns:
        str: The response generated by the reflective AI agent.
    """
    draft = model.generate_content(prompt).text
    print("Draft response: \n", draft)
    reflection_prompt = f"Review the following response for improvements:\n\n{draft}\n\nProvide a revised version with enhancements."

    review = model.generate_content(reflection_prompt).text
    print("Reflection review: \n", review)
    return review